name: Update CSS Customization

on:
  push:
    paths:
      - 'src/json/tokensStudio/customization.json'
  pull_request:
    paths:
      - 'src/json/tokensStudio/customization.json'

permissions:
  contents: write
  issues: write
  pull-requests: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'

      - name: Install dependencies
        run: npm install

      - name: Run script to update CSS
        run: node scripts/update-css.js

      - name: Commit and push if necessary
        run: |
          git config --global user.name 'santossilva'
          git config --global user.email 'santossilva@gmail.com'
          git add src/css/customization.css  # Adjusted to correct relative path
          git commit -m "Update CSS based on JSON changes" || echo "No changes to commit"
          git push origin HEAD:main  # Ensure the branch name is correct
